### ISSUE TITLE
[Bug] Getting Started: TypeError: cannot pickle 'property' object

### ISSUE THREAD

**Issue by chhanganivarun** [AIcrowd/neurips2020-procgen-starter-kit#15]
On following the Getting Started on README, on running ```./run.sh --train```, I receive this error:
```
(aicrowd_env) 23:16:44  varun varun-ubuntu /media/varun/Data/aicrowd/neurips2020-procgen-starter-kit master
$ ./run.sh --train
           _____                          _ 
     /\   |_   _|                        | |
    /  \    | |  ___ _ __ _____      ____| |
   / /\ \   | | / __| '__/ _ \ \ /\ / / _  |
  / ____ \ _| || (__| | | (_) \ V  V / (_| |
 /_/    \_\_____\___|_|  \___/ \_/\_/ \__,_|
 
Executing: python train.py -f experiments/impala-baseline.yaml --ray-memory 1500000000 --ray-num-cpus 2 --ray-object-store-memory 1000000000
Traceback (most recent call last):
  File "train.py", line 40, in <module>
    load_envs(os.getcwd()) # Load envs
  File "/media/varun/Data/aicrowd/neurips2020-procgen-starter-kit/utils/loader.py", line 62, in load_envs
    _source_file(_file_path)
  File "/media/varun/Data/aicrowd/neurips2020-procgen-starter-kit/utils/loader.py", line 22, in _source_file
    loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/media/varun/Data/aicrowd/neurips2020-procgen-starter-kit/envs/procgen_env_wrapper.py", line 65, in <module>
    registry.register_env(
  File "/media/varun/Data/aicrowd/aicrowd_env/lib/python3.8/site-packages/ray/tune/registry.py", line 86, in register_env
    _global_registry.register(ENV_CREATOR, name, env_creator)
  File "/media/varun/Data/aicrowd/aicrowd_env/lib/python3.8/site-packages/ray/tune/registry.py", line 112, in register
    self._to_flush[(category, key)] = pickle.dumps(value)
  File "/media/varun/Data/aicrowd/aicrowd_env/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 72, in dumps
    cp.dump(obj)
  File "/media/varun/Data/aicrowd/aicrowd_env/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 617, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'property' object
```

**Comment by chhanganivarun** [comment]
@spMohanty

**Comment by chhanganivarun** [comment]
The error was due to problem with cloudpickle on python3

https://discourse.aicrowd.com/t/typeerror-cannot-pickle-property-object/3110
